# Generated by Django 3.1.3 on 2020-11-13 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dapp', '0004_auto_20201109_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dapp',
            name='phonenumber',
            field=models.BigIntegerField(null=True),
        ),
    ]
